import { GateType, GateInfo, GateCategory } from "../types/quantum";

// Define all gates with their properties
export const GATE_INFO: Record<GateType, GateInfo> = {
  // Single-qubit gates
  [GateType.HADAMARD]: {
    type: GateType.HADAMARD,
    name: "Hadamard",
    symbol: "H",
    description: "Creates superposition",
    category: GateCategory.SINGLE_QUBIT,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.PAULI_X]: {
    type: GateType.PAULI_X,
    name: "Pauli-X",
    symbol: "X",
    description: "Bit-flip (NOT gate)",
    category: GateCategory.SINGLE_QUBIT,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.PAULI_Y]: {
    type: GateType.PAULI_Y,
    name: "Pauli-Y",
    symbol: "Y",
    description: "Y-rotation",
    category: GateCategory.SINGLE_QUBIT,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.PAULI_Z]: {
    type: GateType.PAULI_Z,
    name: "Pauli-Z",
    symbol: "Z",
    description: "Phase-flip",
    category: GateCategory.SINGLE_QUBIT,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.PHASE]: {
    type: GateType.PHASE,
    name: "Phase",
    symbol: "S",
    description: "π/2 phase rotation",
    category: GateCategory.SINGLE_QUBIT,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.PI_8]: {
    type: GateType.PI_8,
    name: "π/8",
    symbol: "T",
    description: "π/4 phase rotation",
    category: GateCategory.SINGLE_QUBIT,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },

  // Quarter turns
  [GateType.SQRT_X]: {
    type: GateType.SQRT_X,
    name: "Square Root of X",
    symbol: "√X",
    description: "Square root of X gate (90° rotation around X-axis)",
    category: GateCategory.ROTATION,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.SQRT_X_DAG]: {
    type: GateType.SQRT_X_DAG,
    name: "Square Root of X Dagger",
    symbol: "√X†",
    description: "Inverse square root of X gate (-90° rotation around X-axis)",
    category: GateCategory.ROTATION,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.SQRT_Y]: {
    type: GateType.SQRT_Y,
    name: "Square Root of Y",
    symbol: "√Y",
    description: "Square root of Y gate (90° rotation around Y-axis)",
    category: GateCategory.ROTATION,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.SQRT_Y_DAG]: {
    type: GateType.SQRT_Y_DAG,
    name: "Square Root of Y Dagger",
    symbol: "√Y†",
    description: "Inverse square root of Y gate (-90° rotation around Y-axis)",
    category: GateCategory.ROTATION,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.SQRT_Z]: {
    type: GateType.SQRT_Z,
    name: "Square Root of Z",
    symbol: "√Z",
    description: "Square root of Z gate (90° rotation around Z-axis)",
    category: GateCategory.ROTATION,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.SQRT_Z_DAG]: {
    type: GateType.SQRT_Z_DAG,
    name: "Square Root of Z Dagger",
    symbol: "√Z†",
    description: "Inverse square root of Z gate (-90° rotation around Z-axis)",
    category: GateCategory.ROTATION,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },

  // Eighth turns
  [GateType.X_4]: {
    type: GateType.X_4,
    name: "X^(1/4)",
    symbol: "X^¼",
    description: "X to the power of 1/4 (45° rotation around X-axis)",
    category: GateCategory.ROTATION,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.X_4_DAG]: {
    type: GateType.X_4_DAG,
    name: "X^(-1/4)",
    symbol: "X^-¼",
    description: "X to the power of -1/4 (-45° rotation around X-axis)",
    category: GateCategory.ROTATION,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.Y_4]: {
    type: GateType.Y_4,
    name: "Y^(1/4)",
    symbol: "Y^¼",
    description: "Y to the power of 1/4 (45° rotation around Y-axis)",
    category: GateCategory.ROTATION,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.Y_4_DAG]: {
    type: GateType.Y_4_DAG,
    name: "Y^(-1/4)",
    symbol: "Y^-¼",
    description: "Y to the power of -1/4 (-45° rotation around Y-axis)",
    category: GateCategory.ROTATION,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.Z_4]: {
    type: GateType.Z_4,
    name: "Z^(1/4)",
    symbol: "Z^¼",
    description: "Z to the power of 1/4 (45° rotation around Z-axis)",
    category: GateCategory.ROTATION,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.Z_4_DAG]: {
    type: GateType.Z_4_DAG,
    name: "Z^(-1/4)",
    symbol: "Z^-¼",
    description: "Z to the power of -1/4 (-45° rotation around Z-axis)",
    category: GateCategory.ROTATION,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },

  // Parameterized rotation gates
  [GateType.RX]: {
    type: GateType.RX,
    name: "Rx",
    symbol: "Rx",
    description: "Rotation around X-axis by a specified angle",
    category: GateCategory.ROTATION,
    qubits: 1,
    isParameterized: true,
    isDisplay: false,
    isControl: false,
  },
  [GateType.RY]: {
    type: GateType.RY,
    name: "Ry",
    symbol: "Ry",
    description: "Rotation around Y-axis by a specified angle",
    category: GateCategory.ROTATION,
    qubits: 1,
    isParameterized: true,
    isDisplay: false,
    isControl: false,
  },
  [GateType.RZ]: {
    type: GateType.RZ,
    name: "Rz",
    symbol: "Rz",
    description: "Rotation around Z-axis by a specified angle",
    category: GateCategory.ROTATION,
    qubits: 1,
    isParameterized: true,
    isDisplay: false,
    isControl: false,
  },
  [GateType.PHASE_BY_A]: {
    type: GateType.PHASE_BY_A,
    name: "Z^A",
    symbol: "Z^A",
    description: "Z rotation by input A",
    category: GateCategory.ROTATION,
    qubits: 1,
    isParameterized: true,
    isDisplay: false,
    isControl: false,
  },
  [GateType.PHASE_BY_MINUS_A]: {
    type: GateType.PHASE_BY_MINUS_A,
    name: "Z^-A",
    symbol: "Z^-A",
    description: "Z rotation by negative input A",
    category: GateCategory.ROTATION,
    qubits: 1,
    isParameterized: true,
    isDisplay: false,
    isControl: false,
  },
  [GateType.X_BY_A]: {
    type: GateType.X_BY_A,
    name: "X^A",
    symbol: "X^A",
    description: "X rotation by input A",
    category: GateCategory.ROTATION,
    qubits: 1,
    isParameterized: true,
    isDisplay: false,
    isControl: false,
  },
  [GateType.X_BY_MINUS_A]: {
    type: GateType.X_BY_MINUS_A,
    name: "X^-A",
    symbol: "X^-A",
    description: "X rotation by negative input A",
    category: GateCategory.ROTATION,
    qubits: 1,
    isParameterized: true,
    isDisplay: false,
    isControl: false,
  },
  [GateType.Y_BY_A]: {
    type: GateType.Y_BY_A,
    name: "Y^A",
    symbol: "Y^A",
    description: "Y rotation by input A",
    category: GateCategory.ROTATION,
    qubits: 1,
    isParameterized: true,
    isDisplay: false,
    isControl: false,
  },
  [GateType.Y_BY_MINUS_A]: {
    type: GateType.Y_BY_MINUS_A,
    name: "Y^-A",
    symbol: "Y^-A",
    description: "Y rotation by negative input A",
    category: GateCategory.ROTATION,
    qubits: 1,
    isParameterized: true,
    isDisplay: false,
    isControl: false,
  },

  // Multi-qubit gates
  [GateType.CNOT]: {
    type: GateType.CNOT,
    name: "Controlled-NOT",
    symbol: "CNOT",
    description:
      "Two-qubit gate that flips the target qubit if the control qubit is |1⟩",
    category: GateCategory.MULTI_QUBIT,
    qubits: 2,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.SWAP]: {
    type: GateType.SWAP,
    name: "SWAP",
    symbol: "SWAP",
    description: "Swaps the state of two qubits",
    category: GateCategory.MULTI_QUBIT,
    qubits: 2,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.TOFFOLI]: {
    type: GateType.TOFFOLI,
    name: "Toffoli",
    symbol: "TOFFOLI",
    description: "Three-qubit gate, also known as CCNOT",
    category: GateCategory.MULTI_QUBIT,
    qubits: 3,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },

  // Arithmetic gates
  [GateType.INCREMENT]: {
    type: GateType.INCREMENT,
    name: "Increment",
    symbol: "INC",
    description: "Increments the value of the target register",
    category: GateCategory.ARITHMETIC,
    qubits: 2,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.DECREMENT]: {
    type: GateType.DECREMENT,
    name: "Decrement",
    symbol: "DEC",
    description: "Decrements the value of the target register",
    category: GateCategory.ARITHMETIC,
    qubits: 2,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.ADD_A]: {
    type: GateType.ADD_A,
    name: "Add A",
    symbol: "+A",
    description: "Adds the value of register A to the target register",
    category: GateCategory.ARITHMETIC,
    qubits: 2,
    isParameterized: true,
    isDisplay: false,
    isControl: false,
  },
  [GateType.SUBTRACT_A]: {
    type: GateType.SUBTRACT_A,
    name: "Subtract A",
    symbol: "-A",
    description: "Subtracts the value of register A from the target register",
    category: GateCategory.ARITHMETIC,
    qubits: 2,
    isParameterized: true,
    isDisplay: false,
    isControl: false,
  },
  [GateType.MULTIPLY_A]: {
    type: GateType.MULTIPLY_A,
    name: "Multiply by A",
    symbol: "×A",
    description: "Multiplies the target register by the value of register A",
    category: GateCategory.ARITHMETIC,
    qubits: 2,
    isParameterized: true,
    isDisplay: false,
    isControl: false,
  },
  [GateType.MULTIPLY_A_INVERSE]: {
    type: GateType.MULTIPLY_A_INVERSE,
    name: "Multiply by A Inverse",
    symbol: "×A⁻¹",
    description: "Multiplies the target register by the inverse of register A",
    category: GateCategory.ARITHMETIC,
    qubits: 2,
    isParameterized: true,
    isDisplay: false,
    isControl: false,
  },

  // Modular arithmetic gates
  [GateType.INCREMENT_MOD_R]: {
    type: GateType.INCREMENT_MOD_R,
    name: "Increment mod R",
    symbol: "INC mod R",
    description: "Increments the value of the target register modulo R",
    category: GateCategory.MODULAR,
    qubits: 2,
    isParameterized: true,
    isDisplay: false,
    isControl: false,
  },
  [GateType.DECREMENT_MOD_R]: {
    type: GateType.DECREMENT_MOD_R,
    name: "Decrement mod R",
    symbol: "DEC mod R",
    description: "Decrements the value of the target register modulo R",
    category: GateCategory.MODULAR,
    qubits: 2,
    isParameterized: true,
    isDisplay: false,
    isControl: false,
  },
  [GateType.ADD_A_MOD_R]: {
    type: GateType.ADD_A_MOD_R,
    name: "Add A mod R",
    symbol: "+A mod R",
    description: "Adds the value of register A to the target register modulo R",
    category: GateCategory.MODULAR,
    qubits: 2,
    isParameterized: true,
    isDisplay: false,
    isControl: false,
  },
  [GateType.SUBTRACT_A_MOD_R]: {
    type: GateType.SUBTRACT_A_MOD_R,
    name: "Subtract A mod R",
    symbol: "-A mod R",
    description:
      "Subtracts the value of register A from the target register modulo R",
    category: GateCategory.MODULAR,
    qubits: 2,
    isParameterized: true,
    isDisplay: false,
    isControl: false,
  },
  [GateType.MULTIPLY_A_MOD_R]: {
    type: GateType.MULTIPLY_A_MOD_R,
    name: "Multiply by A mod R",
    symbol: "×A mod R",
    description:
      "Multiplies the target register by the value of register A modulo R",
    category: GateCategory.MODULAR,
    qubits: 2,
    isParameterized: true,
    isDisplay: false,
    isControl: false,
  },
  [GateType.MULTIPLY_A_MOD_R_INVERSE]: {
    type: GateType.MULTIPLY_A_MOD_R_INVERSE,
    name: "Multiply by A Inverse mod R",
    symbol: "×A⁻¹ mod R",
    description:
      "Multiplies the target register by the inverse of register A modulo R",
    category: GateCategory.MODULAR,
    qubits: 2,
    isParameterized: true,
    isDisplay: false,
    isControl: false,
  },

  // Bit manipulation gates
  [GateType.REVERSE_BITS]: {
    type: GateType.REVERSE_BITS,
    name: "Reverse Bits",
    symbol: "REV",
    description: "Reverses the order of bits in the target register",
    category: GateCategory.BIT_MANIPULATION,
    qubits: 2,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.INTERLEAVE_BITS]: {
    type: GateType.INTERLEAVE_BITS,
    name: "Interleave Bits",
    symbol: "INTLV",
    description: "Interleaves the bits of two registers",
    category: GateCategory.BIT_MANIPULATION,
    qubits: 4,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.DEINTERLEAVE_BITS]: {
    type: GateType.DEINTERLEAVE_BITS,
    name: "Deinterleave Bits",
    symbol: "DEINTLV",
    description: "Deinterleaves the bits of a register into two registers",
    category: GateCategory.BIT_MANIPULATION,
    qubits: 4,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.CYCLE_BITS]: {
    type: GateType.CYCLE_BITS,
    name: "Cycle Bits",
    symbol: "CYCLE",
    description: "Cycles the bits in the target register",
    category: GateCategory.BIT_MANIPULATION,
    qubits: 3,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.REVERSE_CYCLE_BITS]: {
    type: GateType.REVERSE_CYCLE_BITS,
    name: "Reverse Cycle Bits",
    symbol: "REV CYCLE",
    description: "Cycles the bits in the target register in reverse",
    category: GateCategory.BIT_MANIPULATION,
    qubits: 3,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },

  // Fourier transform gates
  [GateType.QFT]: {
    type: GateType.QFT,
    name: "Quantum Fourier Transform",
    symbol: "QFT",
    description: "Applies the Quantum Fourier Transform to the target register",
    category: GateCategory.FOURIER,
    qubits: 2,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.QFT_INVERSE]: {
    type: GateType.QFT_INVERSE,
    name: "Inverse Quantum Fourier Transform",
    symbol: "QFT⁻¹",
    description:
      "Applies the Inverse Quantum Fourier Transform to the target register",
    category: GateCategory.FOURIER,
    qubits: 2,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },

  // Phase gradient gates
  [GateType.PHASE_GRADIENT]: {
    type: GateType.PHASE_GRADIENT,
    name: "Phase Gradient",
    symbol: "PhGrad",
    description: "Applies a phase gradient to the target register",
    category: GateCategory.FOURIER,
    qubits: 2,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.PHASE_DEGRADIENT]: {
    type: GateType.PHASE_DEGRADIENT,
    name: "Phase Degradient",
    symbol: "PhDegrad",
    description: "Applies a phase degradient to the target register",
    category: GateCategory.FOURIER,
    qubits: 2,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },

  // Comparison gates
  [GateType.LESS_THAN]: {
    type: GateType.LESS_THAN,
    name: "Less Than",
    symbol: "A<B",
    description: "Sets the target qubit if register A is less than register B",
    category: GateCategory.COMPARISON,
    qubits: 2,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.GREATER_THAN]: {
    type: GateType.GREATER_THAN,
    name: "Greater Than",
    symbol: "A>B",
    description:
      "Sets the target qubit if register A is greater than register B",
    category: GateCategory.COMPARISON,
    qubits: 2,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.LESS_EQUAL]: {
    type: GateType.LESS_EQUAL,
    name: "Less Than or Equal",
    symbol: "A≤B",
    description:
      "Sets the target qubit if register A is less than or equal to register B",
    category: GateCategory.COMPARISON,
    qubits: 2,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.GREATER_EQUAL]: {
    type: GateType.GREATER_EQUAL,
    name: "Greater Than or Equal",
    symbol: "A≥B",
    description:
      "Sets the target qubit if register A is greater than or equal to register B",
    category: GateCategory.COMPARISON,
    qubits: 2,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.EQUAL]: {
    type: GateType.EQUAL,
    name: "Equal",
    symbol: "A=B",
    description: "Sets the target qubit if register A is equal to register B",
    category: GateCategory.COMPARISON,
    qubits: 2,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.NOT_EQUAL]: {
    type: GateType.NOT_EQUAL,
    name: "Not Equal",
    symbol: "A≠B",
    description:
      "Sets the target qubit if register A is not equal to register B",
    category: GateCategory.COMPARISON,
    qubits: 2,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },

  // Control gates
  [GateType.CONTROL]: {
    type: GateType.CONTROL,
    name: "Control",
    symbol: "•",
    description: "Control point that activates when the qubit is |1⟩",
    category: GateCategory.CONTROL,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: true,
  },
  [GateType.ANTI_CONTROL]: {
    type: GateType.ANTI_CONTROL,
    name: "Anti-Control",
    symbol: "○",
    description: "Control point that activates when the qubit is |0⟩",
    category: GateCategory.CONTROL,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: true,
  },
  [GateType.X_CONTROL]: {
    type: GateType.X_CONTROL,
    name: "X-Control",
    symbol: "⊕",
    description:
      "Control point that activates when the qubit is in X-basis |+⟩",
    category: GateCategory.CONTROL,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: true,
  },
  [GateType.X_ANTI_CONTROL]: {
    type: GateType.X_ANTI_CONTROL,
    name: "X-Anti-Control",
    symbol: "⊖",
    description:
      "Control point that activates when the qubit is in X-basis |-⟩",
    category: GateCategory.CONTROL,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: true,
  },
  [GateType.Y_CONTROL]: {
    type: GateType.Y_CONTROL,
    name: "Y-Control",
    symbol: "⊙",
    description:
      "Control point that activates when the qubit is in Y-basis |i⟩",
    category: GateCategory.CONTROL,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: true,
  },
  [GateType.Y_ANTI_CONTROL]: {
    type: GateType.Y_ANTI_CONTROL,
    name: "Y-Anti-Control",
    symbol: "⊘",
    description:
      "Control point that activates when the qubit is in Y-basis |-i⟩",
    category: GateCategory.CONTROL,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: true,
  },
  [GateType.Z_PARITY_CONTROL]: {
    type: GateType.Z_PARITY_CONTROL,
    name: "Z-Parity Control",
    symbol: "⨁",
    description:
      "Control point that activates based on the parity of multiple qubits in Z-basis",
    category: GateCategory.CONTROL,
    qubits: 2,
    isParameterized: false,
    isDisplay: false,
    isControl: true,
  },
  [GateType.Y_PARITY_CONTROL]: {
    type: GateType.Y_PARITY_CONTROL,
    name: "Y-Parity Control",
    symbol: "⨂",
    description:
      "Control point that activates based on the parity of multiple qubits in Y-basis",
    category: GateCategory.CONTROL,
    qubits: 2,
    isParameterized: false,
    isDisplay: false,
    isControl: true,
  },
  [GateType.X_PARITY_CONTROL]: {
    type: GateType.X_PARITY_CONTROL,
    name: "X-Parity Control",
    symbol: "⨀",
    description:
      "Control point that activates based on the parity of multiple qubits in X-basis",
    category: GateCategory.CONTROL,
    qubits: 2,
    isParameterized: false,
    isDisplay: false,
    isControl: true,
  },

  // Post-selection gates
  [GateType.POST_SELECT_ON]: {
    type: GateType.POST_SELECT_ON,
    name: "Post-Select On",
    symbol: "!0",
    description: "Post-selects the qubit to be in the |0⟩ state",
    category: GateCategory.POST_SELECTION,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.POST_SELECT_OFF]: {
    type: GateType.POST_SELECT_OFF,
    name: "Post-Select Off",
    symbol: "!1",
    description: "Post-selects the qubit to be in the |1⟩ state",
    category: GateCategory.POST_SELECTION,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.POST_SELECT_X]: {
    type: GateType.POST_SELECT_X,
    name: "Post-Select X",
    symbol: "!+",
    description: "Post-selects the qubit to be in the |+⟩ state",
    category: GateCategory.POST_SELECTION,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.POST_SELECT_ANTI_X]: {
    type: GateType.POST_SELECT_ANTI_X,
    name: "Post-Select Anti-X",
    symbol: "!-",
    description: "Post-selects the qubit to be in the |-⟩ state",
    category: GateCategory.POST_SELECTION,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.POST_SELECT_Y]: {
    type: GateType.POST_SELECT_Y,
    name: "Post-Select Y",
    symbol: "!i",
    description: "Post-selects the qubit to be in the |i⟩ state",
    category: GateCategory.POST_SELECTION,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.POST_SELECT_ANTI_Y]: {
    type: GateType.POST_SELECT_ANTI_Y,
    name: "Post-Select Anti-Y",
    symbol: "!-i",
    description: "Post-selects the qubit to be in the |-i⟩ state",
    category: GateCategory.POST_SELECTION,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },

  // Detector gates
  [GateType.Z_DETECTOR]: {
    type: GateType.Z_DETECTOR,
    name: "Z-Detector",
    symbol: "Z?",
    description: "Detects if the qubit is in the Z-basis",
    category: GateCategory.DETECTOR,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.X_DETECTOR]: {
    type: GateType.X_DETECTOR,
    name: "X-Detector",
    symbol: "X?",
    description: "Detects if the qubit is in the X-basis",
    category: GateCategory.DETECTOR,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.Y_DETECTOR]: {
    type: GateType.Y_DETECTOR,
    name: "Y-Detector",
    symbol: "Y?",
    description: "Detects if the qubit is in the Y-basis",
    category: GateCategory.DETECTOR,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.Z_DETECT_CONTROL_CLEAR]: {
    type: GateType.Z_DETECT_CONTROL_CLEAR,
    name: "Z-Detect Control Clear",
    symbol: "Z?•",
    description:
      "Detects if the qubit is in the Z-basis and clears the control",
    category: GateCategory.DETECTOR,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.X_DETECT_CONTROL_CLEAR]: {
    type: GateType.X_DETECT_CONTROL_CLEAR,
    name: "X-Detect Control Clear",
    symbol: "X?•",
    description:
      "Detects if the qubit is in the X-basis and clears the control",
    category: GateCategory.DETECTOR,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.Y_DETECT_CONTROL_CLEAR]: {
    type: GateType.Y_DETECT_CONTROL_CLEAR,
    name: "Y-Detect Control Clear",
    symbol: "Y?•",
    description:
      "Detects if the qubit is in the Y-basis and clears the control",
    category: GateCategory.DETECTOR,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },

  // Input gates
  [GateType.INPUT_A]: {
    type: GateType.INPUT_A,
    name: "Input A",
    symbol: "A",
    description: "Input register A",
    category: GateCategory.INPUT,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.INPUT_B]: {
    type: GateType.INPUT_B,
    name: "Input B",
    symbol: "B",
    description: "Input register B",
    category: GateCategory.INPUT,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.INPUT_R]: {
    type: GateType.INPUT_R,
    name: "Input R",
    symbol: "R",
    description: "Input register R (modulus)",
    category: GateCategory.INPUT,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.SET_A]: {
    type: GateType.SET_A,
    name: "Set A",
    symbol: "SetA",
    description: "Set the value of register A",
    category: GateCategory.INPUT,
    qubits: 1,
    isParameterized: true,
    isDisplay: false,
    isControl: false,
  },
  [GateType.SET_B]: {
    type: GateType.SET_B,
    name: "Set B",
    symbol: "SetB",
    description: "Set the value of register B",
    category: GateCategory.INPUT,
    qubits: 1,
    isParameterized: true,
    isDisplay: false,
    isControl: false,
  },
  [GateType.SET_R]: {
    type: GateType.SET_R,
    name: "Set R",
    symbol: "SetR",
    description: "Set the value of register R (modulus)",
    category: GateCategory.INPUT,
    qubits: 1,
    isParameterized: true,
    isDisplay: false,
    isControl: false,
  },

  // Measurement
  [GateType.MEASURE]: {
    type: GateType.MEASURE,
    name: "Measure",
    symbol: "M",
    description: "Measures the qubit in the computational basis",
    category: GateCategory.MEASUREMENT,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },

  // Display gates
  [GateType.AMPLITUDE_DISPLAY]: {
    type: GateType.AMPLITUDE_DISPLAY,
    name: "Amplitude Display",
    symbol: "Amps",
    description: "Displays the amplitudes of the quantum state",
    category: GateCategory.DISPLAY,
    qubits: 1,
    isParameterized: false,
    isDisplay: true,
    isControl: false,
  },
  [GateType.PROBABILITY_DISPLAY]: {
    type: GateType.PROBABILITY_DISPLAY,
    name: "Probability Display",
    symbol: "Chance",
    description: "Displays the probabilities of the quantum state",
    category: GateCategory.DISPLAY,
    qubits: 1,
    isParameterized: false,
    isDisplay: true,
    isControl: false,
  },
  [GateType.SAMPLE_DISPLAY]: {
    type: GateType.SAMPLE_DISPLAY,
    name: "Sample Display",
    symbol: "Sample",
    description: "Displays a random sample from the quantum state",
    category: GateCategory.DISPLAY,
    qubits: 1,
    isParameterized: false,
    isDisplay: true,
    isControl: false,
  },
  [GateType.DENSITY_MATRIX_DISPLAY]: {
    type: GateType.DENSITY_MATRIX_DISPLAY,
    name: "Density Matrix Display",
    symbol: "Density",
    description: "Displays the density matrix of the quantum state",
    category: GateCategory.DISPLAY,
    qubits: 1,
    isParameterized: false,
    isDisplay: true,
    isControl: false,
  },
  [GateType.BLOCH_DISPLAY]: {
    type: GateType.BLOCH_DISPLAY,
    name: "Bloch Sphere Display",
    symbol: "Bloch",
    description: "Displays the quantum state on the Bloch sphere",
    category: GateCategory.DISPLAY,
    qubits: 1,
    isParameterized: false,
    isDisplay: true,
    isControl: false,
  },

  // Special gates
  [GateType.SPACER]: {
    type: GateType.SPACER,
    name: "Spacer",
    symbol: " ",
    description: "Empty spacer gate",
    category: GateCategory.SPECIAL,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.ZERO]: {
    type: GateType.ZERO,
    name: "Zero",
    symbol: "0",
    description: "Always outputs zero (impossible gate)",
    category: GateCategory.SPECIAL,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.IMAGINARY]: {
    type: GateType.IMAGINARY,
    name: "Imaginary",
    symbol: "i",
    description: "Multiplies by i",
    category: GateCategory.SPECIAL,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.ANTI_IMAGINARY]: {
    type: GateType.ANTI_IMAGINARY,
    name: "Anti-Imaginary",
    symbol: "-i",
    description: "Multiplies by -i",
    category: GateCategory.SPECIAL,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.SQRT_IMAGINARY]: {
    type: GateType.SQRT_IMAGINARY,
    name: "Square Root of i",
    symbol: "√i",
    description: "Multiplies by the square root of i",
    category: GateCategory.SPECIAL,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
  [GateType.ANTI_SQRT_IMAGINARY]: {
    type: GateType.ANTI_SQRT_IMAGINARY,
    name: "Square Root of -i",
    symbol: "√-i",
    description: "Multiplies by the square root of -i",
    category: GateCategory.SPECIAL,
    qubits: 1,
    isParameterized: false,
    isDisplay: false,
    isControl: false,
  },
};

// Group gates by category
export const GATES_BY_CATEGORY: Record<GateCategory, GateType[]> =
  Object.values(GateCategory).reduce((acc, category) => {
    acc[category] = Object.values(GateType).filter(
      (gateType) => GATE_INFO[gateType]?.category === category
    );
    return acc;
  }, {} as Record<GateCategory, GateType[]>);

// Define toolbox groups similar to Quirk
export const TOP_TOOLBOX_GROUPS = [
  {
    hint: "Probes",
    gates: [
      GateType.MEASURE,
      undefined,
      GateType.POST_SELECT_OFF,
      GateType.POST_SELECT_ON,
      GateType.ANTI_CONTROL,
      GateType.CONTROL,
    ],
  },
  {
    hint: "Displays",
    gates: [
      undefined,
      undefined,
      GateType.DENSITY_MATRIX_DISPLAY,
      GateType.BLOCH_DISPLAY,
      GateType.PROBABILITY_DISPLAY,
      GateType.AMPLITUDE_DISPLAY,
    ],
  },
  {
    hint: "Half Turns",
    gates: [
      GateType.PAULI_Z,
      GateType.SWAP,
      GateType.PAULI_Y,
      undefined,
      GateType.PAULI_X,
      GateType.HADAMARD,
    ],
  },
  {
    hint: "Quarter Turns",
    gates: [
      GateType.SQRT_Z,
      GateType.SQRT_Z_DAG,
      GateType.SQRT_Y,
      GateType.SQRT_Y_DAG,
      GateType.SQRT_X,
      GateType.SQRT_X_DAG,
    ],
  },
  {
    hint: "Eighth Turns",
    gates: [
      GateType.Z_4,
      GateType.Z_4_DAG,
      GateType.Y_4,
      GateType.Y_4_DAG,
      GateType.X_4,
      GateType.X_4_DAG,
    ],
  },
  {
    hint: "Spinning",
    gates: [
      GateType.PHASE_BY_A,
      GateType.PHASE_BY_MINUS_A,
      GateType.Y_BY_A,
      GateType.Y_BY_MINUS_A,
      GateType.X_BY_A,
      GateType.X_BY_MINUS_A,
    ],
  },
  {
    hint: "Parametrized",
    gates: [
      GateType.RZ,
      undefined,
      GateType.RY,
      undefined,
      GateType.RX,
      undefined,
    ],
  },
];

export const BOTTOM_TOOLBOX_GROUPS = [
  {
    hint: "X/Y Probes",
    gates: [
      GateType.X_ANTI_CONTROL,
      GateType.X_CONTROL,
      GateType.Y_ANTI_CONTROL,
      GateType.Y_CONTROL,
      GateType.POST_SELECT_ANTI_X,
      GateType.POST_SELECT_X,
      GateType.POST_SELECT_ANTI_Y,
      GateType.POST_SELECT_Y,
    ],
  },
  {
    hint: "Order",
    gates: [
      GateType.REVERSE_BITS,
      undefined,
      GateType.CYCLE_BITS,
      GateType.REVERSE_CYCLE_BITS,
      GateType.INTERLEAVE_BITS,
      GateType.DEINTERLEAVE_BITS,
    ],
  },
  {
    hint: "Frequency",
    gates: [
      GateType.QFT,
      GateType.QFT_INVERSE,
      undefined,
      undefined,
      GateType.PHASE_GRADIENT,
      GateType.PHASE_DEGRADIENT,
    ],
  },
  {
    hint: "Inputs",
    gates: [
      GateType.INPUT_A,
      GateType.SET_A,
      GateType.INPUT_B,
      GateType.SET_B,
      GateType.INPUT_R,
      GateType.SET_R,
    ],
  },
  {
    hint: "Arithmetic",
    gates: [
      GateType.INCREMENT,
      GateType.DECREMENT,
      GateType.ADD_A,
      GateType.SUBTRACT_A,
      GateType.MULTIPLY_A,
      GateType.MULTIPLY_A_INVERSE,
    ],
  },
  {
    hint: "Compare",
    gates: [
      GateType.LESS_THAN,
      GateType.GREATER_THAN,
      GateType.LESS_EQUAL,
      GateType.GREATER_EQUAL,
      GateType.EQUAL,
      GateType.NOT_EQUAL,
    ],
  },
  {
    hint: "Modular",
    gates: [
      GateType.INCREMENT_MOD_R,
      GateType.DECREMENT_MOD_R,
      GateType.ADD_A_MOD_R,
      GateType.SUBTRACT_A_MOD_R,
      GateType.MULTIPLY_A_MOD_R,
      GateType.MULTIPLY_A_MOD_R_INVERSE,
    ],
  },
  {
    hint: "Scalar",
    gates: [
      GateType.SPACER,
      GateType.ZERO,
      undefined,
      undefined,
      GateType.IMAGINARY,
      GateType.ANTI_IMAGINARY,
      GateType.SQRT_IMAGINARY,
      GateType.ANTI_SQRT_IMAGINARY,
    ],
  },
];

// Initial states mapping
export const INITIAL_STATES_TO_GATES: Map<string | undefined, GateType[]> =
  new Map([
    [undefined, []],
    ["1", [GateType.PAULI_X]],
    ["+", [GateType.HADAMARD]],
    ["-", [GateType.HADAMARD, GateType.PAULI_Z]],
    ["i", [GateType.HADAMARD, GateType.SQRT_Z]],
    ["-i", [GateType.HADAMARD, GateType.SQRT_Z_DAG]],
  ]);
